from fpdf import FPDF
import os
from datetime import datetime

class ReportingService:
    def __init__(self):
        self.reports_dir = os.path.join(os.path.dirname(__file__), '../../reports')
        os.makedirs(self.reports_dir, exist_ok=True)

    def generate_threat_report(self, analysis_result: dict):
        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_fill_color(17, 20, 27) # Dark theme color
        pdf.rect(0, 0, 210, 40, 'F')
        
        pdf.set_font("Arial", 'B', 24)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 20, "CyberForge AI - Security Audit", ln=True, align='C')
        
        pdf.set_font("Arial", size=10)
        pdf.cell(0, 10, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align='C')
        
        pdf.set_text_color(0, 0, 0)
        pdf.ln(20)
        
        # Risk Summary
        risk_score = analysis_result.get('risk_score', 0)
        status = "CRITICAL" if risk_score > 70 else "WARNING" if risk_score > 30 else "SAFE"
        
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(0, 10, f"Threat Status: {status} ({risk_score}%)", ln=True)
        pdf.ln(5)
        
        # Content Analysis
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, "Analyzed Content Preview:", ln=True)
        pdf.set_font("Arial", size=10)
        pdf.multi_cell(0, 5, analysis_result.get('text_preview', 'N/A'))
        pdf.ln(10)
        
        # Detailed Breakdown
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, "Intelligence Breakdown:", ln=True)
        pdf.set_font("Arial", size=10)
        breakdown = analysis_result.get('breakdown', {})
        for key, val in breakdown.items():
            pdf.cell(0, 8, f"- {key.replace('_', ' ').title()}: {val}%", ln=True)
        pdf.ln(10)
        
        # AI Logic (Signals)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, "Risk Signals Detected:", ln=True)
        pdf.set_font("Arial", size=10)
        for sig in analysis_result.get('signals', []):
            msg = sig.get('message', sig) if isinstance(sig, dict) else sig
            pdf.multi_cell(0, 8, f"[*] {msg}")
        pdf.ln(10)
        
        # Suggested Actions
        pdf.set_fill_color(240, 240, 240)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, "Recommended Mitigation Strategy:", ln=True, fill=True)
        pdf.set_font("Arial", size=10)
        pdf.multi_cell(0, 8, analysis_result.get('suggested_action', "No specific action required."))
        
        # Footer
        pdf.set_y(-30)
        pdf.set_font("Arial", 'I', 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 10, "This report was generated by CyberForge AI Hybrid AI Engine. For educational purposes only.", align='C')
        
        report_filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        report_path = os.path.join(self.reports_dir, report_filename)
        pdf.output(report_path)
        
        return report_filename, report_path
